server:
  port: 8000
  undertow:
    direct-buffers: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # ip-address:
    prefer-ip-address: true
spring:
  application:
    name: pay-server